spring:
  data:
    redis:
      host: 192.168.1.196 #redis服务器地址
      port: 6379  #redis服务器端口号
      database: 0 #默认使用0号数据库（数据库索引）
      timeout: 1800000  #连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 20  #连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  #最大阻塞等待时间（负数表示没有限制）
          max-idle: 5 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接